#!/usr/bin/env bash
# -----------------------------------------------------------------------------
set -euo pipefail # Stop running the script on first error...
# -----------------------------------------------------------------------------
K8S_MANIFESTS="./k8s/vms/testvm.yaml"
K8S_VM_NAME=$(cat $K8S_MANIFESTS | yq -e '.metadata.name')

# Connect to the VM
echo "Connecting to VM: $K8S_VM_NAME..."
./bin/virtctl vnc ${K8S_VM_NAME}
