#!/usr/bin/env bash
# -----------------------------------------------------------------------------
set -euo pipefail # Stop running the script on first error...
# -----------------------------------------------------------------------------
# Download the Windows ISO image
DOWNLOAD_DIR="./dist"
DOWNLOAD_URL="https://go.microsoft.com/fwlink/p/?LinkID=2195443&clcid=0x409&culture=en-us&country=US"
DOWNLOAD_TAG="win.iso"

mkdir -p $DOWNLOAD_DIR
curl -sL -C - -o "$DOWNLOAD_DIR/$DOWNLOAD_TAG" $DOWNLOAD_URL