#!/usr/bin/env bash
# -----------------------------------------------------------------------------
set -euo pipefail # Stop running the script on first error...
# -----------------------------------------------------------------------------
# Download the CDI Upload Proxy
kubectl apply -f ./k8s/upload-proxy.yaml